format = """
$username\
[î‚´](fg:#1a5fb4 bg:#3584e4)\
$directory\
[î‚´](fg:#3584e4 bg:#99c1f1)\
$git_branch\
$git_status\
[î‚´](fg:#99c1f1)\
$python\
$character"""

[username]
style_user = 'fg:white bg:#1a5fb4 bold'
style_root = 'fg:red bg:#1a5fb4 bold'
format = '[$user:]($style)'
disabled = false
show_always = true

[directory]
style = "fg:white bg:#3584e4"
format = "[ $path ]($style)"
truncation_length = 8
truncation_symbol = "â€¦/"

[directory.substitutions]
"Documents" = "Documents ó°ˆ™"
"Downloads" = "Downloads ï€™"
"Pictures" = "Pictures ï€¾"

[python]
symbol = " ğŸ"
format = '[${symbol}${pyenv_prefix}(${version} )(\($virtualenv\) )]($style)'

[git_branch]
symbol = "ï˜"
style = "fg:#5e5c64 bg:#99c1f1"
format = '[ $symbol $branch ]($style)'

[git_status]
style = "bg:#99c1f1"
format = "[$all_status$ahead_behind]($style)"
conflicted = "ğŸ³"
ahead = "â‡¡${count}"
behind = "â‡£${count}"
diverged = "â‡•â‡¡${ahead_count}â‡£${behind_count}"
untracked = "ğŸ†•${count}"
stashed = "ğŸ“¦"
modified = "ğŸ“${count}"
staged = "âœ…${count}"
renamed = "â¡ï¸${count}"
deleted = "ğŸ—‘ï¸ ${count}"
